# Generated by Django 4.0.5 on 2022-08-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one_onetomany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
