# Generated by Django 4.0.5 on 2022-08-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one_onetoone', '0002_lesson_onetoone_teacher_onetoone_delete_lesson_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson_onetoone',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='Teacher_onetoone',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name_onetoone',
            new_name='lesson_name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_teacher_onetoone',
            new_name='lesson_teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name_onetoone',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='picture_onetoone',
            new_name='picture',
        ),
    ]
