# Generated by Django 4.0.5 on 2022-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_four_teacherprofie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
