# Generated by Django 4.0.5 on 2022-08-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_four_teacherprofie', '0002_teacherprofile_picture_alter_teacherprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_four_teacherprofie.teacherprofile')),
            ],
        ),
    ]
