# Generated by Django 4.0.5 on 2022-08-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_three_manytomany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
    ]
